<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AcploCartDoctrineORM\Module'                               => __DIR__ . '/Module.php',
  'AcploCartDoctrineORM\Adapter\CartAdapterInterface'         => __DIR__ . '/src/AcploCartDoctrineORM/Adapter/CartAdapterInterface.php',
  'AcploCartDoctrineORM\Adapter\DoctrineCartAdapter'          => __DIR__ . '/src/AcploCartDoctrineORM/Adapter/DoctrineCartAdapter.php',
  'AcploCartDoctrineORM\Entity\Cart'                          => __DIR__ . '/src/AcploCartDoctrineORM/Entity/Cart.php',
  'AcploCartDoctrineORM\Entity\CartEntityInterface'           => __DIR__ . '/src/AcploCartDoctrineORM/Entity/CartEntityInterface.php',
  'AcploCartDoctrineORM\Entity\CartItem'                      => __DIR__ . '/src/AcploCartDoctrineORM/Entity/CartItem.php',
  'AcploCartDoctrineORM\Entity\CartItemInterface'             => __DIR__ . '/src/AcploCartDoctrineORM/Entity/CartItemInterface.php',
  'AcploCartDoctrineORM\Hydrator\CartItemHydrator'            => __DIR__ . '/src/AcploCartDoctrineORM/Hydrator/CartItemHydrator.php',
  'AcploCartDoctrineORM\Listener\CartListener'                => __DIR__ . '/src/AcploCartDoctrineORM/Listener/CartListener.php',
  'AcploCartDoctrineORM\Listener\Factory\CartListenerFactory' => __DIR__ . '/src/AcploCartDoctrineORM/Listener/Factory/CartListenerFactory.php',
  'AcploCartDoctrineORM\Service\CartService'                  => __DIR__ . '/src/AcploCartDoctrineORM/Service/CartService.php',
  'AcploCartDoctrineORM\Service\CartServiceInterface'         => __DIR__ . '/src/AcploCartDoctrineORM/Service/CartServiceInterface.php',
  'AcploCartDoctrineORM\Service\Factory\CartServiceFactory'   => __DIR__ . '/src/AcploCartDoctrineORM/Service/Factory/CartServiceFactory.php',
);
